# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_url', models.URLField(blank=True, null=True)),
                ('period_end_date', models.DateField()),
                ('period_length', models.IntegerField(choices=[(6, '6 Months'), (9, '9 Months'), (12, 'Full Year')], default=12, help_text='Length of the period for which the results belong to')),
                ('earnings', models.IntegerField(help_text='Profit after tax for the period')),
                ('debt', models.IntegerField(blank=True, help_text='Total Borrowed Funds', null=True)),
                ('equity', models.IntegerField(help_text="Shareholders' Equity")),
                ('current_assets', models.IntegerField()),
                ('current_liabilities', models.IntegerField()),
                ('EPS', models.DecimalField(decimal_places=2, help_text='profit attributable to equity         holders of the Company divided by outstanding shares', max_digits=6)),
                ('outstanding_shares', models.IntegerField(help_text='Total Number of Issued shares')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.Company', unique_for_date='period_end_date')),
            ],
        ),
    ]
