# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField(choices=[(3, '3 Months'), (6, 'Half Year'), (9, '9 Months'), (12, 'Full Year')], default=9, help_text='Length of the period for which the results belong to')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='period_end_date',
        ),
        migrations.RemoveField(
            model_name='result',
            name='period_length',
        ),
    ]
